default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: postgres
  password:

development:
  <<: *default
  database: rails-docker-app_development

test:
  <<: *default
  database: rails-docker-app_test

production:
  <<: *default
  database: rails-docker-app_production
  username: rails-docker-app
  password: <%= ENV['RAILS-DOCKER-APP_DATABASE_PASSWORD'] %>
